#!/bin/bash

runaways=`ipcs | grep wilcox_+ | cut -d" " -f2`

echo "pre culling"
echo "$runaways"

for x in $runaways
do
    ipcrm $x
done

echo "post culling"

runawaysPost=`ipcs | grep wilcox_+ | cut -d" " -f2`
echo "$runawaysPost"


echo "done"
