#!/bin/bash

proc="a.out"

if [ $# -gt 0 ];
then 
    proc=$1
fi


runaways=`ps -ef | grep wilcox_+ | grep "$proc" | cut -d" " -f2`


runawaysCount=`ps -ef | grep wilcox_+ | grep "$proc" | cut -d" " -f2 | wc -l`

if [ $runawaysCount -gt 1 ]
then

echo -e "pre culling"
ps -ef | grep wilcox | grep "$proc"

for x in $runaways
do
    kill $x
    echo "Killed PID $x"
done

echo -e "post culling"
ps -ef | grep wilcox | grep "$proc"

fi

echo -e "done"
