#!/bin/bash
# WILLEM WILCOX, DR. ALLEN, CSC460, MU

while true; 
do
    # Display "Peanuts> " tag
    read -p "Peanuts> " curr_cmd sec_cmd

    # Check for exit command
    if [ "$curr_cmd" == "nutsout" ]; then
        echo "Oh nuts...quittin' already? Okay...Bye Bye!"
        break
    fi

    # Switch Case for processing commands
    case $curr_cmd in
	# "nutty" does ???
	"nutty")
  		echo "Preparing Time Machine"
		sleep 1
		echo "."
		sleep 1
		echo "."
		sleep 1
		echo "."
		sleep 3
		echo " "
		echo -e "\033[31mSegmentation Fault (Core dumped)\033[0m"
		echo " "
		sleep 1
		echo "Nuts...Maybe next time..."
		;;
	# "showcase filename" displays file with up/dwn scroll
	"showcase")
		less "$sec_cmd"
		;;
	
	# "nutcall userid"
	"nutcall")
		userchecked=`grep "$sec_cmd" /etc/passwd | cut -d":" -f5 | cut -d"," -f1,3`
		echo $userchecked
		;;
	# "nutlist" displays names of users currently logged in
	"nutlist")
		thoseon=`who | cut -d" " -f1`
	
		for x in $thoseon
		do
   			 grep $x /etc/passwd | cut -d":" -f5 | cut -d"," -f1
		done
		echo		
		;;
	
	# "nutstuff" displays contents of current directory
	"nutstuff")
		ls -l # I prefer the look of the listed version
		;;
	
	# "helpnuts" display commands and syntax
	"helpnuts")
		cat helplist
		;;
	
	# "bignut" spawns new bash shell
	"bignut")
		bash	
		;;
	
	# "spybear arg/s" calls spybear
	"spybear")
		source spybear $sec_cmd		
		;;
	
	# "peanutbutter filename" calls vim on filename
	"peanutbutter")
		vim $sec_cmd 		
		;;
	
	# "hate" calls spybear
	"hate")
		echo "...is bad for your heart" 		
		;;

	# default case
    	*)
		echo "BAD NUT... TRY ~ helpnuts ~ ..."
		;;
    esac
done

